### ISSUE TITLE
repository not found, token with permission

### ISSUE THREAD

**Issue by adelightday** [FreedomIntelligence/LongLLaVA#11]
Hi, I'm trying to run the model locally. Once I run the command line inference, python cli.py --model_dir path-to-longllava, it got an error as follow

<img width="1049" alt="Screenshot 2024-10-14 at 13 18 02" src="https://github.com/user-attachments/assets/06da213b-87b0-48ea-8c13-a7281b45e997">

<img width="1440" alt="Screenshot 2024-10-14 at 13 18 21" src="https://github.com/user-attachments/assets/416fc8ab-646b-4b73-90be-9a8151b1dddc">

Do you have any solution to my problem?

Look forward to hear from you soon

**Comment by wangxidong06** [comment]
You need to download model from [huggingface](https://huggingface.co/FreedomIntelligence/LongLLaVA-9B) first.

**Comment by adelightday** [comment]
Thank you for your reply!
