### ISSUE TITLE
Appreciation for the Influence on VLM and Inquiry about LLM Foundation

### ISSUE THREAD

**Issue by CuriousCat-7** [FreedomIntelligence/LongLLaVA#2]
Hey! I'm really impressed by your work on VLM. It has a huge impact for the MLLM area.
I wonder about the LLM in your VLM. Did you train it from 0? Or use a pre - trained model like "ai21labs/Jamba - v0.1"? Thanks!

**Comment by wangxidong06** [comment]
we use the pre - trained model "ai21labs/Jamba - v0.1"
