### ISSUE TITLE
Missing supporting init.sh and VisionJamba found when running MultiImageSFT.sh

### ISSUE THREAD

**Issue by MXC66ai** [FreedomIntelligence/LongLLaVA#3]
!bash /content/LongLLaVA/MultiImageSFT.sh
/content/LongLLaVA/MultiImageSFT.sh: line 3: /sds_wangby/group_conda_envs/init.sh: No such file or directory
/content/LongLLaVA/MultiImageSFT.sh: line 4: conda: command not found
/content/LongLLaVA/MultiImageSFT.sh: line 18: cd: /wangbenyou/xidong/VisionJamba: No such file or directory

**Comment by wangxidong06** [comment]
sorry for confusion, we are still working on code, the code will be released soon (Approximately Sep 16th )，also the enviroment

**Comment by wangxidong06** [comment]
We have updated the code, please try again, we are looking forward to your reply.
