### ISSUE TITLE
ImportError: cannot import name 'LlavaPhiForCausalLM' from 'llava.model' 

### ISSUE THREAD

**Issue by Jeremy-J-J** [FreedomIntelligence/LongLLaVA#5]
when execute the shell `python cli.py --model_dir /path/to/LongLLaVA`
the error occurred
```
ImportError: cannot import name 'LlavaPhiForCausalLM' from 'llava.model' 
```
how to solve it ?

**Comment by wangxidong06** [comment]
[I remove that line](https://github.com/FreedomIntelligence/LongLLaVA/blob/main/cli.py), this is for baseline test, and we do not contain them in this repo, so I just remove the line. If you have any question please feel free to ask me.
