### ISSUE TITLE
Architecture of LongLLaVA

### ISSUE THREAD

**Issue by maxin-cn** [FreedomIntelligence/LongLLaVA#6]
Thank you very much for sharing the code. I'm particularly interested in the architecture of LongLLaVA as shown in Figure 2 of the paper. However, since I’m not very familiar with LLMs, I had some difficulty locating this specific structure in the code. Would you be able to provide me with a direct link to it? I would greatly appreciate it. Thank you again!

**Comment by wangxidong06** [comment]
Thanks for your Recognition, the architecture of LLM is [here](https://github.com/FreedomIntelligence/LongLLaVA/blob/main/llava/model/language_model/Jamba/modeling_jamba.py).  If you have any question, please feel free to ask me.
