### ISSUE TITLE
the role of moe

### ISSUE THREAD

**Issue by maxin-cn** [FreedomIntelligence/LongLLaVA#7]
Thanks for your great work! 
I have read your paper and noticed that you use the Mamba MoE layer. I'm curious about the rationale behind using this specific layer, as I couldn't find an explanation in the paper. Is it chosen primarily for scalability?

**Comment by wangxidong06** [comment]
Sorry for the delayed response, I was on vacation this past week.
For MoE we have two reasons :.
1. on the one hand the Jamba model itself has this architecture, as motivated by the authors in the article.
2. on the other hand the MoE architecture is the one that gives better performance with the same training FLOPs.

Besides, we also used the Dense model (9B) in the latest version of the paper, and the related model will be released soon, so stay tuned.

**Comment by maxin-cn** [comment]
Thanks for your reply and hope you had a great holiday!
